<?php namespace atlasmobile\queue\console\controllers;

use atlasmobile\models\FailedJobs;
use atlasmobile\queue\Job;
use atlasmobile\queue\Queue;
use Yii;
use yii\base\Exception;
use yii\console\Controller;

/**
 * Queue Process Command
 *
 * Class QueueController
 *
 * atlas. 2015
 * @author Eduard Maximovich <edward.vstock@gmail.com>
 * @package atlasmobile\queue\console\controllers
 */
class QueueController extends Controller
{
	public static $TAG = __CLASS__;
	public $sleep = 1;
	public $tries = 3;
	public $queueName = 'default';
	public $queueObjectName = 'queue';
	public $storeFailedJobs = false;

	public function beforeAction($action) {
		if ($this->storeFailedJobs === 'true' || $this->storeFailedJobs === '1') {
			$this->storeFailedJobs = true;
		}
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	/**
	 * Process a job
	 *
	 * @throws \Exception
	 */
	public function actionWork() {
		$this->process();
	}

	/**
	 * @return bool
	 * @throws \Exception
	 */
	protected function process() {
		/** @var Queue $queue */
		$queue = Yii::$app->{$this->queueObjectName};
		/** @var Job $job */
		$job = $queue->pop($this->queueName);

		if ($job instanceof Job) {
			try {
				$job->run();
				return true;
			} catch (\Exception $e) {
				Yii::error($e->getTraceAsString(), self::$TAG);
				$payload = $job->getEncodedPayload();

				if (!isset($payload->data)) {
					$payload->data = new \stdClass();
				}

				if (isset($payload->data) && isset($payload->data->tries) && $payload->data->tries < $this->tries) {
					$payload->data->tries++;
					Yii::info("Tries " . $payload->data->tries . PHP_EOL, self::$TAG);
				} else if (!isset($payload->data->tries)) {
					$payload->data->tries = 1;
					Yii::info("Tries " . $payload->data->tries . PHP_EOL, self::$TAG);
				} else {
					Yii::error("TRY #" . $payload->data->tries . ': ' . $e->getTraceAsString(), self::$TAG);
					if ($this->storeFailedJobs) {
						$this->storeFailed($payload->job, $payload->data->tries, $payload);
					}
					throw $e;
				}
				$queue->push($payload->job, $payload->data, $job->getQueueName());

				throw $e;
			}
		}
		return false;
	}

	private function storeFailed($className, $tries, $payload) {
		try {
			FailedJobs::add($className, $tries, $payload);
		} catch (Exception $ex) {
			throw new \yii\db\Exception('Table failed_jobs not created. Please, run: queue/table-failed');
		}

	}

	/**
	 * Continuously process jobs
	 *
	 * @return bool
	 * @throws \Exception
	 */
	public function actionListen() {
		while (true) {
			$cmd = $this->buildWorkerCommand();
			echo exec($cmd, $out);
			echo implode(PHP_EOL, $out);
			sleep($this->sleep);
		}
	}

	private function buildWorkerCommand($actionName = 'work') {
		$cmd = [];
		$cmd[] = PHP_BINARY;
		$cmd[] = Yii::$app->basePath . '/../yii queue/' . $actionName;
		$params = [];
		foreach ($this->options(null) AS $option) {
			if (in_array($option, parent::options(null))) continue;
			$params['--' . $option] = $this->$option;
		}

		$out = implode(' ', $cmd) . ' ';
		foreach ($params AS $k => $v) {
			$out .= $k . '=' . $v;
			$out .= ' ';
		}

		return $out;
	}

	public function options($actionID) {
		return array_merge(parent::options($actionID), [
			'tries', 'sleep', 'queueName', 'queueObjectName', 'storeFailedJobs'
		]);
	}

	/**
	 * Creates table with failed jobs
	 */
	public function actionTableFailed() {
		$this->run('migrate/up', [
			'migrationPath' => '@vendor/atlasmobile/yii2-queue/src/migrations'
		]);
	}
}
